name: "CI: Build and Push image"
on:
  push:
    branches:
      - 'master'

jobs:
  docker_image_:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push pycdc
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: kamuri/pycdc:latest
          target: pycdc
      -
        name: Build and push pycdas
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: kamuri/pycdas:latest
          target: pycdas
